'use client'

import { toast } from 'sonner'
import QuizSection from './QuizSection'

export default function MobileNotesOverlay({ isOpen, onClose, noteData }) {
  const handleCopy = () => {
    if (!noteData) return
    const content = document.getElementById('mobileActualNotes').innerText
    navigator.clipboard.writeText(content)
    toast.success('Notes copied to clipboard!')
  }

  const handleDownload = async () => {
    if (!noteData) return
    toast.info('Preparing PDF download...')

    const safeStyles = `
      * { box-sizing: border-box !important; margin: 0 !important; padding: 0 !important; }
      body {
        font-family: Arial, Helvetica, sans-serif !important;
        color: #1e293b !important;
        background: #ffffff !important;
        padding: 40px !important;
        font-size: 14px !important;
        line-height: 1.7 !important;
      }
      h1 { font-size: 22px !important; font-weight: 700 !important; color: #0f172a !important;
           margin-bottom: 16px !important; padding-bottom: 10px !important;
           border-bottom: 2px solid #e2e8f0 !important; }
      h2 { font-size: 17px !important; font-weight: 700 !important; color: #1e293b !important;
           margin-top: 24px !important; margin-bottom: 10px !important; }
      h3 { font-size: 15px !important; font-weight: 600 !important; color: #334155 !important;
           margin-top: 16px !important; margin-bottom: 8px !important; }
      p  { margin-bottom: 12px !important; color: #334155 !important; }
      ul, ol { padding-left: 22px !important; margin-bottom: 14px !important; }
      li { color: #334155 !important; margin-bottom: 5px !important; }
      strong, b { font-weight: 700 !important; color: #0f172a !important; }
      .summary { background: #eef2ff !important; border-left: 4px solid #818cf8 !important;
                 padding: 14px 18px !important; border-radius: 8px !important; margin: 20px 0 !important; }
      .definition { background: #f0fdf4 !important; border: 1px solid #bbf7d0 !important;
                    padding: 12px 16px !important; border-radius: 8px !important; margin: 14px 0 !important; }
      .definition p { color: #14532d !important; font-style: italic !important; }
      table { border-collapse: collapse !important; width: 100% !important; margin-bottom: 16px !important; }
      th, td { border: 1px solid #e2e8f0 !important; padding: 8px 12px !important; }
      th { background: #f8fafc !important; font-weight: 700 !important; }
      code { background: #f1f5f9 !important; padding: 2px 5px !important; font-family: monospace !important; }
      pre { background: #f1f5f9 !important; padding: 14px !important; border-radius: 6px !important; margin-bottom: 16px !important; }
      blockquote { border-left: 3px solid #cbd5e1 !important; padding-left: 14px !important; color: #64748b !important; margin: 12px 0 !important; }
    `

    try {
      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF('p', 'mm', 'a4')

      const pageWidth = doc.internal.pageSize.getWidth()
      const margin = 20
      const contentWidth = pageWidth - (margin * 2)
      let cursorY = 25

      // Helper to handle page breaks
      const checkPageBreak = (neededHeight) => {
        if (cursorY + neededHeight > 280) {
          doc.addPage()
          cursorY = margin
          return true
        }
        return false
      }

      // 1. Add Header / Brand
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('GENERATED BY STUDYMASTER', margin, 15)
      doc.line(margin, 17, pageWidth - margin, 17)

      // 2. Add Title
      doc.setFontSize(22)
      doc.setTextColor(15, 23, 42) // Slate 900
      const titleLines = doc.splitTextToSize(noteData.title || 'Study Notes', contentWidth)
      doc.text(titleLines, margin, cursorY + 5)
      cursorY += (titleLines.length * 10) + 15

      // 3. Simple HTML Parsing-lite
      const tempDiv = document.createElement('div')
      tempDiv.innerHTML = noteData.content

      const processNode = (node) => {
        if (node.nodeType === 3) { // Text node
          const text = node.textContent.trim()
          if (!text) return

          doc.setFont('helvetica', 'normal')
          doc.setFontSize(11)
          doc.setTextColor(51, 65, 85) // Slate 700

          const lines = doc.splitTextToSize(text, contentWidth)
          checkPageBreak(lines.length * 6)
          doc.text(lines, margin, cursorY)
          cursorY += (lines.length * 6) + 4
        } else if (node.nodeType === 1) { // Element node
          const tag = node.tagName.toLowerCase()

          if (['h1', 'h2', 'h3'].includes(tag)) {
            const size = tag === 'h1' ? 18 : tag === 'h2' ? 16 : 14
            doc.setFont('helvetica', 'bold')
            doc.setFontSize(size)
            doc.setTextColor(30, 41, 59) // Slate 800

            const text = node.innerText.trim()
            const lines = doc.splitTextToSize(text, contentWidth)
            checkPageBreak((lines.length * size * 0.4) + 10)
            cursorY += 5
            doc.text(lines, margin, cursorY)
            cursorY += (lines.length * size * 0.4) + 8
          } else if (tag === 'p') {
            const text = node.innerText.trim()
            if (!text) return
            doc.setFont('helvetica', 'normal')
            doc.setFontSize(11)
            doc.setTextColor(51, 65, 85)
            const lines = doc.splitTextToSize(text, contentWidth)
            checkPageBreak(lines.length * 6)
            doc.text(lines, margin, cursorY)
            cursorY += (lines.length * 6) + 6
          } else if (tag === 'li') {
            const text = node.innerText.trim()
            if (!text) return
            doc.setFont('helvetica', 'normal')
            doc.setFontSize(11)
            doc.setTextColor(51, 65, 85)
            const lines = doc.splitTextToSize("• " + text, contentWidth)
            checkPageBreak(lines.length * 6)
            doc.text(lines, margin, cursorY)
            cursorY += (lines.length * 6) + 3
          } else {
            // Recursively process children
            node.childNodes.forEach(processNode)
          }
        }
      }

      tempDiv.childNodes.forEach(processNode)

      // 4. Footer
      const totalPages = doc.internal.getNumberOfPages()
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setTextColor(180, 180, 180)
        doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, 285)
      }

      doc.save(`${noteData.title?.replace(/\s+/g, '_') || 'StudyMaster_Notes'}.pdf`)
      toast.success('PDF downloaded successfully!')
    } catch (err) {
      console.error('Custom PDF Gen Error:', err)
      toast.error('Direct PDF generation failed. Using print fallback...')
      const w = window.open('', '_blank')
      if (!w) { toast.error('Pop-up blocked. Please allow pop-ups.'); return }
      w.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8">
        <title>${noteData.title || 'Notes'}</title>
        <style>
          body{font-family:Arial,sans-serif;color:#1e293b;padding:40px;font-size:14px;line-height:1.7}
          h1{font-size:22px;font-weight:700;border-bottom:2px solid #e2e8f0;padding-bottom:10px;margin-bottom:16px}
          h2{font-size:17px;font-weight:700;margin-top:24px;margin-bottom:10px}
          h3{font-size:15px;font-weight:600;margin-top:16px;margin-bottom:8px}
          p{margin-bottom:12px} ul,ol{padding-left:22px;margin-bottom:14px} li{margin-bottom:5px}
          @media print{body{padding:20px}@page{margin:1in 0.75in;size:A4}}
        </style>
        </head><body>${noteData.content}<script>window.onload=function(){window.print();window.onafterprint=function(){window.close()}}<\/script></body></html>`)
      w.document.close()
    }
  }


  const handlePrint = () => {
    if (!noteData) return
    const w = window.open('', '_blank')
    if (!w) { toast.error('Pop-up blocked. Please allow pop-ups.'); return }
    w.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8">
      <title>${noteData.title || 'Notes'}</title>
      <style>
        body{font-family:Arial,sans-serif;color:#1e293b;padding:40px;font-size:14px;line-height:1.7}
        h1{font-size:22px;font-weight:700;border-bottom:2px solid #e2e8f0;padding-bottom:10px;margin-bottom:16px}
        h2{font-size:17px;font-weight:700;margin-top:24px;margin-bottom:10px}
        h3{font-size:15px;font-weight:600;margin-top:16px;margin-bottom:8px}
        p{margin-bottom:12px} ul,ol{padding-left:22px;margin-bottom:14px} li{margin-bottom:5px}
        @media print{body{padding:20px}@page{margin:1in 0.75in;size:A4}}
      </style>
      </head><body>${noteData.content}<script>window.onload=function(){window.print();window.onafterprint=function(){window.close()}}<\/script></body></html>`)
    w.document.close()
  }

  return (
    <div
      className={`md:hidden fixed inset-0 z-[60] bg-white notes-overlay flex flex-col transition-transform duration-400 ${isOpen ? 'translate-y-0' : 'translate-y-full'
        }`}
      style={{
        transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      }}
    >
      {/* Header */}
      <div className="h-16 border-b border-slate-100 px-4 flex items-center justify-between">
        <span className="font-semibold text-sm truncate max-w-[200px]">
          {noteData?.title || 'Notes'}
        </span>
        <button
          onClick={onClose}
          className="w-8 h-8 flex items-center justify-center rounded-full bg-slate-100"
        >
          <iconify-icon icon="solar:close-circle-linear" width="20" height="20"></iconify-icon>
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6" id="mobileNotesContent">
        {!noteData ? (
          <div className="flex flex-col items-center justify-center h-full text-center space-y-4">
            <iconify-icon icon="solar:notebook-linear" width="48" height="48" className="text-slate-200"></iconify-icon>
            <p className="text-slate-500 text-sm">No notes generated yet.</p>
          </div>
        ) : (
          <div
            id="mobileActualNotes"
            className="animate-in fade-in duration-700 sm-notes-container"
            dangerouslySetInnerHTML={{ __html: noteData.content }}
          />
        )}

        {noteData && (
          <QuizSection
            quizData={noteData.quizId}
            noteContent={noteData.content}
          />
        )}
      </div>

      {/* Footer Actions */}
      <div className="p-4 border-t border-slate-100 flex gap-2">
        <button
          onClick={handlePrint}
          disabled={!noteData}
          className="flex-1 bg-slate-900 text-white py-3 rounded-xl text-sm font-medium disabled:bg-slate-300 flex items-center justify-center gap-2"
        >
          <iconify-icon icon="solar:printer-linear" width="18" height="18"></iconify-icon>
          Print Notes
        </button>
        <button
          onClick={handleCopy}
          disabled={!noteData}
          className="w-12 h-12 flex items-center justify-center border border-slate-200 rounded-xl disabled:opacity-50"
        >
          <iconify-icon icon="solar:copy-linear" width="20" height="20"></iconify-icon>
        </button>
      </div>
    </div>
  )
}

