'use client'

import { toast } from 'sonner'
import { useRef } from 'react'
import QuizSection from './QuizSection'

export default function NotesDisplay({ noteData }) {
  const handleCopy = () => {
    if (!noteData) return
    const content = document.getElementById('actualNotes').innerText
    navigator.clipboard.writeText(content)
    toast.success('Notes copied to clipboard!')
  }

  const handleDownload = async () => {
    if (!noteData) return
    toast.info('Preparing PDF download...')

    const safeStyles = `
      * { box-sizing: border-box !important; margin: 0 !important; padding: 0 !important; }
      body {
        font-family: Arial, Helvetica, sans-serif !important;
        color: #1e293b !important;
        background: #ffffff !important;
        padding: 40px !important;
        font-size: 14px !important;
        line-height: 1.7 !important;
      }
      h1 { font-size: 22px !important; font-weight: 700 !important; color: #0f172a !important;
           margin-bottom: 16px !important; padding-bottom: 10px !important;
           border-bottom: 2px solid #e2e8f0 !important; }
      h2 { font-size: 17px !important; font-weight: 700 !important; color: #1e293b !important;
           margin-top: 24px !important; margin-bottom: 10px !important; }
      h3 { font-size: 15px !important; font-weight: 600 !important; color: #334155 !important;
           margin-top: 16px !important; margin-bottom: 8px !important; }
      p  { margin-bottom: 12px !important; color: #334155 !important; }
      ul, ol { padding-left: 22px !important; margin-bottom: 14px !important; }
      li { color: #334155 !important; margin-bottom: 5px !important; }
      strong, b { font-weight: 700 !important; color: #0f172a !important; }
      .summary { background: #eef2ff !important; border-left: 4px solid #818cf8 !important;
                 padding: 14px 18px !important; border-radius: 8px !important; margin: 20px 0 !important; }
      .definition { background: #f0fdf4 !important; border: 1px solid #bbf7d0 !important;
                    padding: 12px 16px !important; border-radius: 8px !important; margin: 14px 0 !important; }
      .definition p { color: #14532d !important; font-style: italic !important; }
      table { border-collapse: collapse !important; width: 100% !important; margin-bottom: 16px !important; }
      th, td { border: 1px solid #e2e8f0 !important; padding: 8px 12px !important; }
      th { background: #f8fafc !important; font-weight: 700 !important; }
      code { background: #f1f5f9 !important; padding: 2px 5px !important; font-family: monospace !important; }
      pre { background: #f1f5f9 !important; padding: 14px !important; border-radius: 6px !important; margin-bottom: 16px !important; }
      blockquote { border-left: 3px solid #cbd5e1 !important; padding-left: 14px !important; color: #64748b !important; margin: 12px 0 !important; }
    `

    try {
      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF('p', 'mm', 'a4')

      const pageWidth = doc.internal.pageSize.getWidth()
      const margin = 20
      const contentWidth = pageWidth - (margin * 2)
      let cursorY = 25

      // Helper to handle page breaks
      const checkPageBreak = (neededHeight) => {
        if (cursorY + neededHeight > 280) {
          doc.addPage()
          cursorY = margin
          return true
        }
        return false
      }

      // 1. Add Header / Brand
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('GENERATED BY STUDYMASTER', margin, 15)
      doc.line(margin, 17, pageWidth - margin, 17)

      // 2. Add Title
      doc.setFontSize(22)
      doc.setTextColor(15, 23, 42) // Slate 900
      const titleLines = doc.splitTextToSize(noteData.title || 'Study Notes', contentWidth)
      doc.text(titleLines, margin, cursorY + 5)
      cursorY += (titleLines.length * 10) + 15

      // 3. Simple HTML Parsing-lite
      const tempDiv = document.createElement('div')
      tempDiv.innerHTML = noteData.content

      const processNode = (node) => {
        if (node.nodeType === 3) { // Text node
          const text = node.textContent.trim()
          if (!text) return

          doc.setFont('helvetica', 'normal')
          doc.setFontSize(11)
          doc.setTextColor(51, 65, 85) // Slate 700

          const lines = doc.splitTextToSize(text, contentWidth)
          checkPageBreak(lines.length * 6)
          doc.text(lines, margin, cursorY)
          cursorY += (lines.length * 6) + 4
        } else if (node.nodeType === 1) { // Element node
          const tag = node.tagName.toLowerCase()

          if (['h1', 'h2', 'h3'].includes(tag)) {
            const size = tag === 'h1' ? 18 : tag === 'h2' ? 16 : 14
            doc.setFont('helvetica', 'bold')
            doc.setFontSize(size)
            doc.setTextColor(30, 41, 59) // Slate 800

            const text = node.innerText.trim()
            const lines = doc.splitTextToSize(text, contentWidth)
            checkPageBreak((lines.length * size * 0.4) + 10)
            cursorY += 5
            doc.text(lines, margin, cursorY)
            cursorY += (lines.length * size * 0.4) + 8
          } else if (tag === 'p') {
            const text = node.innerText.trim()
            if (!text) return
            doc.setFont('helvetica', 'normal')
            doc.setFontSize(11)
            doc.setTextColor(51, 65, 85)
            const lines = doc.splitTextToSize(text, contentWidth)
            checkPageBreak(lines.length * 6)
            doc.text(lines, margin, cursorY)
            cursorY += (lines.length * 6) + 6
          } else if (tag === 'li') {
            const text = node.innerText.trim()
            if (!text) return
            doc.setFont('helvetica', 'normal')
            doc.setFontSize(11)
            doc.setTextColor(51, 65, 85)
            const lines = doc.splitTextToSize("• " + text, contentWidth)
            checkPageBreak(lines.length * 6)
            doc.text(lines, margin, cursorY)
            cursorY += (lines.length * 6) + 3
          } else {
            // Recursively process children
            node.childNodes.forEach(processNode)
          }
        }
      }

      tempDiv.childNodes.forEach(processNode)

      // 4. Footer
      const totalPages = doc.internal.getNumberOfPages()
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setTextColor(180, 180, 180)
        doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, 285)
      }

      doc.save(`${noteData.title?.replace(/\s+/g, '_') || 'StudyMaster_Notes'}.pdf`)
      toast.success('PDF downloaded successfully!')
    } catch (err) {
      console.error('Custom PDF Gen Error:', err)
      toast.error('Direct PDF generation failed. Using print fallback...')
      downloadViaPrint(noteData)
    }
  }

  const downloadViaPrint = (noteData) => {
    const w = window.open('', '_blank')
    if (!w) { toast.error('Pop-up blocked. Please allow pop-ups.'); return }
    w.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8">
      <title>${noteData.title || 'Notes'}</title>
      <style>
        body{font-family:Arial,sans-serif;color:#1e293b;padding:40px;font-size:14px;line-height:1.7}
        h1{font-size:22px;font-weight:700;border-bottom:2px solid #e2e8f0;padding-bottom:10px;margin-bottom:16px}
        h2{font-size:17px;font-weight:700;margin-top:24px;margin-bottom:10px}
        h3{font-size:15px;font-weight:600;margin-top:16px;margin-bottom:8px}
        p{margin-bottom:12px} ul,ol{padding-left:22px;margin-bottom:14px} li{margin-bottom:5px}
        @media print{body{padding:20px}@page{margin:1in 0.75in;size:A4}}
      </style>
      </head><body>${noteData.content}<script>window.onload=function(){window.print();window.onafterprint=function(){window.close()}}<\/script></body></html>`)
    w.document.close()
    toast.info('Use "Save as PDF" in the print dialog.')
  }

  const handleSave = () => {
    // In our implementation, the note is already saved to DB by Inngest.
    // This button could be for "Adding to Favorites" or just a confirmation.
    toast.success('Notes are already saved in your library!')
  }

  const handleToggleVisibility = async (requestedPublic) => {
    if (!noteData || requestedPublic === noteData.isPublic) return
    try {
      const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/notes/${noteData._id || noteData.id}/visibility`, {
        method: 'PATCH',
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        }
      })
      const data = await response.json()
      if (data.success) {
        toast.success(data.message)
        // Locally update to avoid perceived lag if parent state isn't synced
        noteData.isPublic = data.isPublic
      }
    } catch (error) {
      toast.error('Failed to update visibility')
    }
  }

  if (!noteData) {
    return (
      <section className="hidden md:flex flex-1 flex-col bg-white overflow-hidden items-center justify-center text-center p-8">
        <div className="w-16 h-16 rounded-full bg-slate-50 flex items-center justify-center text-slate-300 mb-4">
          <iconify-icon icon="solar:notebook-linear" width="32" height="32"></iconify-icon>
        </div>
        <div>
          <p className="text-base font-medium text-slate-900">Start your session</p>
          <p className="text-sm text-slate-500 max-w-[240px]">
            Ask the AI to generate notes on any topic and they will appear here.
          </p>
        </div>
      </section>
    )
  }

  return (
    <section className="hidden md:flex flex-1 flex-col bg-white overflow-hidden">
      {/* Toolbar */}
      <div className="h-14 border-b border-slate-100 px-6 flex items-center justify-between bg-white/50 backdrop-blur-sm">
        <div className="flex items-center gap-4">
          <span className="bg-emerald-50 text-emerald-600 px-2 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wider">
            {noteData.tag || 'Biology'}
          </span>
          <h2 className="text-sm font-medium text-slate-700 truncate max-w-[200px]">{noteData.title}</h2>

          <div className="h-4 w-[1px] bg-slate-200"></div>

          <div className="relative flex items-center bg-slate-50 rounded-lg px-2 py-1">
            <iconify-icon icon={noteData.isPublic ? "solar:eye-linear" : "solar:eye-closed-linear"} width="14" height="14" className={noteData.isPublic ? 'text-indigo-600' : 'text-slate-500'}></iconify-icon>
            <select
              value={noteData.isPublic ? 'public' : 'private'}
              onChange={(e) => handleToggleVisibility(e.target.value === 'public')}
              className="bg-transparent text-[10px] font-bold border-none outline-none cursor-pointer pr-4 ml-1 text-slate-700"
            >
              <option value="public">PUBLIC</option>
              <option value="private">PRIVATE</option>
            </select>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={handleCopy} className="p-2 text-slate-400 hover:text-slate-600 transition-colors" title="Copy Content">
            <iconify-icon icon="solar:copy-linear" width="20" height="20"></iconify-icon>
          </button>
          <button onClick={() => downloadViaPrint(noteData)} className="p-2 text-slate-400 hover:text-slate-600 transition-colors" title="Print Note">
            <iconify-icon icon="solar:printer-linear" width="20" height="20"></iconify-icon>
          </button>
          <div className="h-4 w-[1px] bg-slate-200 mx-1"></div>
          <button onClick={handleSave} className="flex items-center gap-2 px-3 py-1.5 bg-indigo-50 text-indigo-600 rounded-lg text-xs font-medium hover:bg-indigo-100 transition-colors">
            <iconify-icon icon="solar:heart-linear" width="16" height="16"></iconify-icon>
            Save to Library
          </button>
        </div>
      </div>

      {/* Notes Content Area */}
      <div className="flex-1 overflow-y-auto p-4 md:p-8 lg:p-12 max-w-4xl mx-auto w-full hide-scrollbar" id="notesContent">
        <div
          id="actualNotes"
          className="animate-in fade-in duration-700 sm-notes-container"
          dangerouslySetInnerHTML={{ __html: noteData.content }}
        />

        {/* Quiz Section */}
        <QuizSection
          quizData={noteData.quizId}
          noteContent={noteData.content}
        />
      </div>
    </section>
  )
}
